### PR TITLE
monitor interval for android

### PR DESCRIPTION
**Pull request by tbenr**
i added android support for monitorInterval

### CODE REVIEW

**Comment by inferusvv** [comment]
@punarinta Why not to merge?

**Comment by inferusvv** [comment]
BTW you can create a patch with [patch-package](https://www.npmjs.com/package/patch-package) lib, so you don't need to fork this repository

**Review by aprilmintacpineda — APPROVED** [review]

**Comment by aprilmintacpineda** [comment]
This should be merged pls @punarinta

**Comment by punarinta** [comment]
Sorry for not supporting the package guys.
I've merged this one and will review the other suggestions/questions.

**Pull request merged**
